[project]
name = "home-kiosk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Adam", email = "astevens9234@outlook.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.100.0",
    "google-api-python-client>=2.95.0",
    "google-auth-httplib2>=0.1.0",
    "google-auth-oauthlib>=1.0.0",
    "psutil>=5.9.0",
    "uvicorn>=0.22.0",
]

[project.scripts]
home-kiosk = "home_kiosk:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
